### ISSUE TITLE
[Bug] Open Data missing in 5.0.0

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1001]
**Describe the bug**
Open data is not showing up in Studies; studies show 0 and api returns an empty array. However, the database contains Open Data  entries, and the log group openDataScrapeHandler shows successful nightly lambda update runs.

_Is this bug fixed in versions > 5.0.0?_

<img width="400" alt="Screen Shot 2022-06-03 at 11 39 31 AM" src="https://user-images.githubusercontent.com/21109191/171900123-3f4ecdf1-dfdc-455b-8dbd-045a39fccaee.png">

**Expected behavior**
Open Data should list open data studies.
<img width="400" alt="Screen Shot 2022-06-03 at 11 39 23 AM" src="https://user-images.githubusercontent.com/21109191/171900125-321d0f16-5313-426e-992e-f61b9c769f7a.png">

**Versions (please complete the following information):**
 - Release Version: 5.0.0

**Comment by maghirardelli** [comment]
Hi @srpiatt ! I was not able to reproduce this bug. Do you have any additional information that could help us determine the root cause? I had an environment that was running 5.1.0 where I could see 102 Open Data Studies in the UI. I reverted that environment to 5.0.0 and could still see all 102 Open Data Studies in the UI.

Are you still experiencing this issue?

Thanks, Marianna

**Comment by srpiatt** [comment]
Something about our cusom network design caused the query parameter to not be decoded when passed to the database. The line at [study-controller.js#L31 ](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/study-controller.js#L31) was changed to `const result = await studyService.list(requestContext, decodeURI(category));`
