### ISSUE TITLE
[Misc] Sagemaker example notebooks

### ISSUE THREAD

**Issue by simranmakwana** [awslabs/service-workbench-on-aws#1046]
**What's on your mind?**
The provided SageMaker example notebooks in SWB require s3 buckets with read and write permissions for users.
Some of our users will not be provisioned an s3 bucket, but we would still like them to be able to run these notebook examples with minimal revisions. Is there an "easy" workaround to using s3 buckets in all the notebooks?

**Versions:**
 - Release Version installed: 5.0.0

fyi @avillach @srpiatt

**Comment by ssvegaraju** [comment]
Hi @simranmakwana, thanks for bringing up this question! I may be missing some context here, but if I'm understanding correctly, would the "Sharing a Study" section of the Service Workbench User Guide answer your question? By default, the Sagemaker notebook doesn't have an S3 bucket attached to it. When you launch the notebook, if you don't attach a study to it, an S3 bucket won't be attached to the notebook either. Let me know if that helps!

Thanks,
Sukeerth

**Comment by simranmakwana** [comment]
Hi Sukeerth, 

Thanks for the quick response! Sorry for not providing enough context in my original post! 
I do not want to attach an S3 bucket to the notebook/workspace, but I do want to run the example Sagemaker jupyter notebook analyses. I'm referring to the notebooks that are located in the SageMaker Examples tab (screenshot attached). Is this possible? 
<img width="1155" alt="Screen Shot 2022-10-07 at 3 57 43 PM" src="https://user-images.githubusercontent.com/56128463/194643641-5ed72576-0488-4c45-b348-b6ad5d0f53f6.png">


Let me know if this clarifies the request, or if you need any additional information.

Best,
Simran

**Comment by maghirardelli** [comment]
Hi Simran! 

Thanks for the additional information! We do not currently support using the example SageMaker notebooks in the SageMaker Examples page. These require more permissions than we allow from the SWB-created SageMaker notebook instances. If you wanted to make this possible, you would need to edit the code base, especially the [sagemaker notebook role](https://github.com/awslabs/service-workbench-on-aws/blob/bcc3cc0cd0a437f83e90fe8a95b68d0f5cc1c06f/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml#L156) to allow the example notebooks to work properly. When I tried using one of the example notebooks, I got an access denied error because the example notebook tried to make an S3 bucket for the notebook. So, it might be a limitation on the SageMaker Notebook Example notebooks' side that require an S3 bucket anyway.

For SWB-created SageMaker Notebooks, you do not need to attach an S3 bucket though! You can create a workspace of type SageMaker Notebook without attaching a Study to it. This will allow your users to use the notebook without having a bucket provisioned.

Let me know if you have further questions,
Marianna
