### ISSUE TITLE
[Feature Request] Propogate All Workspace status to DDB even if status is not a part of predefined mapping

### ISSUE THREAD

**Issue by ElenaKosobrodova** [awslabs/service-workbench-on-aws#1077]
**Describe the bug**
Once Sagemaker Notebook instance is stopped, the user cannot start it again in SWB UI. The workspace status changes to Inactive and the Start button is inactive as well.

When the workspace status is Unknown in SWB UI, the same workspace has status STARTING_FAILED in EnvironmentsSc DynamoDB table. I suspect that there is some kind of mapping and STARTING_FAILED status is not a part of it. For example, COMPLETED status in DynamoDB corresponds to Available in SWB UI. 

**To Reproduce**
1. Start a new Workspace with Sagemaker Notebook instance
2. Stop the instance
3. Try to re-start it

**Expected behavior**
Unknown status should not appear in SWB UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/47466926/206067883-d23f3253-6424-4b7b-bf41-db79844d8105.png)

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by maghirardelli** [comment]
Hello! Thanks for your report. This is the expected behavior of SWB to display Unknown for the statuses that are not necessarily meaningful to users. Is your request that the UI reflect "Starting Failed" instead?

**Comment by Bingjiling** [comment]
Hi @ElenaKosobrodova , 

Thanks for reaching out! If the SageMaker instance fail to re-start, the UI would show Unknown status. This is a behavior by design, as we do not expect the UI to deal with different types of erroring out status of an instance. Could you please check the SageMaker instance in question through AWS Console and see what status it's in?

Thanks,
Yanyu

**Comment by ElenaKosobrodova** [comment]
Thank you for the fast response. I think for troubleshooting purposes it would be more useful to see the actual status instead of Unknown. But I understand that you didn't want to overload users with unnecessary information. 

I checked Sagemaker console. The instance is stopped. I can start and stop it from the console, but workspace status remains Unknown. I could not replicate the issue with other instances yet.

**Comment by DA-Osborne** [comment]
I just thought I would add to this, we also get this randomly for workspaces. This will cause the dynamodb entry to become something service workbench does not recognise, and it displays 'Unknown', with no way for an end user to resolve themselves. Every time this happens, we get support tickets from the users. We then change the dynamodb entry to 'Stopped' again, and then they can start their instance normally. It would be great to modify this behavior so that it either reverts back to stopped by itself, or at least displays the actual status, with a 'reset' button to try and resolve this. Otherwise, it appears to the end users that our platform is buggy.

**Comment by nguyen102** [comment]
I relabeled this issue as a feature request and added it to our backlog.
