### ISSUE TITLE
[Bug] Unclear validation error for the creation of a project 

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1102]
**Describe the bug**
We try to create a project using a newly created Index, get an error for "Input has validation error" but no input field has been marked with any error message.

**To Reproduce**
This is a fresh installation. We just linked to an AWS account and created an Index.

**Expected behavior**
The project should be created or a more informative error message should be displaced.

**Screenshots**
<img width="2343" alt="image" src="https://user-images.githubusercontent.com/9889312/211913426-6cf94be2-a05a-4959-8e18-70321fc13adc.png">

**Versions (please complete the following information):**

version 5.2.5 

**Additional context**

Maybe a budget should be added?

**Comment by BoPeng** [comment]
The problem appears to be caused by a space in project name. It should be an easy fix (add the right error message under the field).

**Comment by kcadette** [comment]
Thank you @BoPeng. We will work on this

**Comment by maghirardelli** [comment]
Hi @BoPeng !

Thanks for bringing this to our attention! I will add a backlog item for our team to consider this in the future! This is likely due to the fact that the form thinks that's a valid value but on sending the request, the space breaks the validation rules for what a "Project Name" can look like as defined [here](https://github.com/awslabs/service-workbench-on-aws/blob/49f46df7598f1f19e9d950db6a952797186d5fbe/addons/addon-base-raas/packages/base-raas-services/lib/schema/create-project.json#L10).

Thanks,
Mar
