### ISSUE TITLE
[Feature Request] rename or remove indexes

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1103]
**Is your feature request related to a problem? Please describe.**
We cannot reuse (rename) or remove an index.

**Describe the solution you'd like**
Be able to remove unused indexes, and/or rename indexes for other purposes.

**Describe alternatives you've considered**
We can modify the underlying database directly if instructions are given.

**Additional context**

**Comment by maghirardelli** [comment]
Hello @BoPeng !

I will add a backlog item for our team to consider this feature request in the future! Thank you for the request!

Thanks,
Mar

**Comment by BoPeng** [comment]
@maghirardelli Could you let me know (or point me to documentation) how to remove or rename indexes from the backend? The index could be used by other users and create further problems so I prefer having it removed, even if I have to do it manually.

**Comment by maghirardelli** [comment]
First, and foremost, we do not recommend editing items manually through DynamoDB like these steps require. Before editing any DynamoDB tables, we suggest you backup the content of those tables just in case. The steps below require access to the AWS Console for the Main Account of SWB.

Secondly, indexes do not cost much. The only resource they consume is space in a DDB Table. Creating a new index should be considered instead of renaming an existing one.

Backing up DynamoDB tables

1. Login to the AWS Console for your Main Account where you deployed SWB.
2. Search for DynamoDB in the top search bar. Click on DynamoDB to open the DynamoDB Console.
3. On the lefthand panel, select “Explore Items”.
4. In the search bar under “Tables”, search for your stage name.
5. Navigate to the table named `<stage>-<regionshortname>-sw-Indexes`. This may be on the second page of results. 
6. Where you see items returned, click “Actions” on the right side. Select “Download results to CSV” to backup the table contents to your local computer.
7. Navigate to the table named `<stage>-<regionshortname>-sw-Projects`. This may be on the second page of results. It should be four results down from the indexes table.
8. Where you see items returned, click “Actions” on the right side. Select “Download results to CSV” to backup the table contents to your local computer.

Renaming an Index

If your index has been connected to a project, you will have to change an item in the Indexes table and any items in the Projects table where `indexId` equals the index name you are renaming. **Without updated the Project as well, you may not be able to connect to, start, stop, or terminate any existing workspaces under that Project.**

1. Backup your DynamoDB tables.
2. In the DynamoDB Console (follow instructions above), in the table named `<stage>-<regionshortname>-sw-Indexes`, navigate to the index you want to rename. 
3. Click on the `id` value for that item to open the item editor. 
4. You may select “JSON view” and toggle on or off “View DynamoDB JSON” so it is easier to read the item. 
5. Update `id` field. A warning should appear that "You are changing the values of the item keys. A transaction is used to delete and recreate the item with the new keys." Tick the box marked "Tick this box to confirm". 
6. Click "Recreate Item" button.
7. To fix any existing projects linked to the old index name, navigate to the table named `<stage>-<regionshortname>-sw-Projects`.
8. For any items in this table where `indexId` equals the name you just replaced, click the `id` of the item to open the item editor.
9. Update the `indexId` field to be the new name from above.

Removing an Index

**If your index has been connected to a project and that project has workspaces in it, you may not be able to connect to, start, stop, or terminate any existing workspaces nor create new ones in that project.**

1. Backup your DynamoDB tables.
2. In the DynamoDB Console (follow instructions above), in the table named `<stage>-<regionshortname>-sw-Indexes`, navigate to the index you want to remove. 
3. Click the checkbox of the item you want to remove.
4. Click “Actions” on the right side. Select “Delete items”. A warning will popup that the action cannot be reversed.
5. Click “Delete” button.
6. If you wanted to clean up a connected project, navigate to the table named `<stage>-<regionshortname>-sw-Projects`.
7. For any items in this table where `indexId` equals the name of the index you just deleted, click the checkbox next to the project id if you want to delete it.
8. Click “Actions” on the right side. Select “Delete items”. A warning will popup that the action cannot be reversed.
9. Click “Delete” button.

Please let me know if you have any questions about these instructions.

**Comment by BoPeng** [comment]
Thanks. We will proceed with caution.

**Comment by BoPeng** [comment]
I followed the instructions, renamed the index and set the `IndexId` field of `dev-va-sw-Projects` to the new ID. However, the following warning message appears when I login to the SWB:

![image](https://user-images.githubusercontent.com/9889312/217680464-57f51f8a-dc40-42d1-9d5d-37e4811013ab.png)

I checked the tables and have not found any other place where the old `IndexId` of `1` is referred.

**Comment by BoPeng** [comment]
Tables `CostApiCaches` and `Environments5c` both have an `IndexId` field. Updating the indexes to the new name fixes the issue.
