### ISSUE TITLE
[Bug] Bucket Policy Limitations

### ISSUE THREAD

**Issue by joelmacey** [awslabs/service-workbench-on-aws#1126]
**Describe the bug**
When a large amount of users or organisation groups use the same study data bucket, the bucket policy exceeds the [20KB limit,](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-iam-policies.html) as SWB amends the existing bucket policy and adds 3 new entries allowing Get, Put and List access to the user/organisation. 
This leads to users not being able to access their uploaded study data when using their workspace.

**To Reproduce**
1. Create multiple users 
2. Create a new study
3. Launch new workspace
4. Repeat until bucket policy is > 20KB
5. When you launch the next workspace, the study data will not be available.

**Expected behavior**
Bucket policy should not exceed the 20KB limit and users should be able to access their study data.

**Screenshots**
Example bucket policy
![image](https://user-images.githubusercontent.com/18387147/218346707-1f70c5d6-4339-4db3-bed9-e3480a8b4613.png)

**Versions :**
- Version 5.2.7
- Modified version of SWB, with custom workspaces, styling, etc - but wouldn't affect bucket policies.

**Comment by SanketD92** [comment]
Hello @joelmacey, we're aware of this particular scaling limitation and it has been added to our backlog.

Thank you for opening this issue and your interest in Service Workbench.

**Comment by tdmalone** [comment]
@joelmacey We worked around this issue by modifying SWB to not adjust the bucket policy at all. This was safe in our case because the administrators with access to the main account are the same as those with access to the hosting accounts, and the bucket access is also controlled on the role added to the launched instances.

In other words, access was being controlled in two places, one that scales (instance roles, in hosting account) and one that doesn't (bucket policy, in main account).

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed
