### ISSUE TITLE
[Bug] Configuring Cognito user Pool Domain fails

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1137]
**Describe the bug**
When installing Service Workbench with fedIdp, the installation process failed during the creation of userPool, with an error message about domain name.

**To Reproduce**
1. set `fedIdpIds`, `fedIdpNames`, `fedIdpDisplayNames`, `fedIdpMetadatas`
2. run the deployment script

**Expected behavior**
Installation should be successful. Instead, the script fails to create `prod-sw-client` during the creation of the `prod-sw-userPool` user pool

**Screenshots**
![image](https://user-images.githubusercontent.com/9889312/222934191-31c9dce3-2727-43c9-aa65-e84b4af03f43.png)

**Versions (please complete the following information):**
 - Release Version installed: current master
 - Is the deployment from a forked version of the repository?

**Additional context**

I am not sure what `Pool Domain` means, but in the client app, the hosted UI looks ok

<img width="2027" alt="image" src="https://user-images.githubusercontent.com/9889312/222934215-a438afd6-5204-453b-9c31-bfed6d034cff.png">

**Comment by BoPeng** [comment]
Similar to #1136 , removing everything from AWS and re-install AWS SW from scratch fixes this problem.

**Comment by rhyslewis-aws** [comment]
I have just seen this issue again.

The last successful log message was:

```
{
    "solutionName": "pj1",
    "envType": "prod",
    "envName": "treprod",
    "logLevel": "info",
    "msg": "Configuring Cognito User Pool Domain"
}
```

and then that was followed by

```
{
    "message": "The domain name contains an invalid character. Domain names can only contain lower-case letters, numbers, and hyphens. Please enter a different name that follows this format: ^[a-z0-9](?:[a-z0-9\\-]{0,61}[a-z0-9])?$",
    "code": "InvalidParameterException",
    "time": "2023-08-15T23:58:30.917Z",
    "requestId": "16e547bf-15f7-4441-8dc8-7be10755d68e",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 49.67319635825929
}
```

There are two CreateUserPoolDomain events that appear in Cloudtrail at the same eventTime.  It is unclear what the order of the events is because they have the same event time

The first has this request:

```
    "errorCode": "InvalidParameterException",
    "errorMessage": "The domain name contains an invalid character. Domain names can only contain lower-case letters, numbers, and hyphens. Please enter a different name that follows this format: ^[a-z0-9](?:[a-z0-9\\-]{0,61}[a-z0-9])?$"
    "requestParameters": {
        "domain": "treprod-xxxxxxxxxxxxxxxxxxxxxx--",  (The obscured values here are lowercase letters and numbers)
        "userPoolId": "ap-southeast-2_XXXXXXXXX"
    },
```
 
and the second is 

```
    "errorCode": "InvalidParameterException",
    "errorMessage": "Domain already associated with another user pool.",
    "requestParameters": {
        "domain": "treprod-pj1",
        "userPoolId": "ap-southeast-2_XXXXXXXXX"
    },
```

The logic for choosing the domain name is here:

https://github.com/awslabs/service-workbench-on-aws/blob/343276851d74f9166c537fa5c3d5bce864aec445/addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js#L509

And my guess is that the first time around the value for providerConfig.userPoolDomain is set here:

https://github.com/awslabs/service-workbench-on-aws/blob/343276851d74f9166c537fa5c3d5bce864aec445/main/solution/post-deployment/config/settings/.defaults.yml#L36

but I can't make sense of how it retries with the other domain.

A few hours later we re-ran it, and everything was fine.  The final Cloudtrail event was 

```
    "requestParameters": {
        "domain": "treprod-prod-pj1",
        "userPoolId": "ap-southeast-2_XXXXXXXXX"
    },
```
