### ISSUE TITLE
[Bug] short usernames do not work at present

### ISSUE THREAD

**Issue by mrgum** [awslabs/service-workbench-on-aws#1162]
**Describe the bug**
Uses with fewer than 3 characters in their username / email prefix cannot use swb

**To Reproduce**
1. Login with a a short username
2. Get the cryptic Network Error

**Expected behavior**
Gain access as any other user

**Screenshots**

**Versions (please complete the following information):**
 - 5.2.7

**Additional context**
I have a fix and will submit pull request

**Comment by mrgum** [comment]
mainline has changed a lot since 5.2.7 so I'll need to create a new environment and move the regex change to addons/addon-base/packages/services/lib/helpers/constants.js instead

**Comment by kpark277** [comment]
Hi @mrgum, the current expectation for SWB is that a username represent the email of the end user, and thus should never be fewer than 3 characters. Due to this being intended functionality, we will not be taking in any changes that would allow user names shorter than 3 characters. Please let us know if you have any questions. Thank you!
