### ISSUE TITLE
[Bug] Connection to SageMaker workspace is allowed even when the source ip is not in the CIDRs list

### ISSUE THREAD

**Issue by paolosach** [awslabs/service-workbench-on-aws#1236]
**Describe the bug**
Connection to SageMaker workspace is allowed even when the source ip is not in the CIDRs list

**To Reproduce**
1. Create a SageMaker workspace
2. Remove your ip from CIDRs list
3. Add a different ip to CIDRs list
4. Click Connect
5. Workspace is correctly opened

**Expected behavior**
Access to workspace shoud be forbidden

**Versions (please complete the following information):**
 - Release Version installed 5.2.11
 - Is the deployment from a forked version of the repository? No

**Comment by janeyuaws** [comment]
Thanks for reaching out. The CIDR restriction is for all workspace types, except SageMaker, so this is running by design.  Please refer to this [page](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/user_guide/sidebar/common/workspaces/create_workspace_study.md) and this v2.0.0 release [notes](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v2.0.0).
