### ISSUE TITLE
[Feature Request] Create and access workspaces that reside in a private VPC/Subnet

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#273]
We are looking at setting up the service workbench but were unsure which AWS account it should be installed in.  It looks like service workbench can add new AWS accounts and manages multiple AWS accounts.  Does that mean that service workbench is essentially acting as the AWS organizations (management) account?  Does that mean we should install service workbench into our org management account or can we install it into one of our org member account?

**Comment by jn1119** [comment]
Hi Khai,

Apologies for the delay in replying. If you have AWS organization setup already, Service Workbench is ideally meant to be installed in your management account (formerly known as master account). Note that there are several concepts like main, master and member account but many customers just end up using the same account for both main and master- I have added a link later that expands those concepts. The idea is for your organization member accounts to be added as member accounts in Service Workbench as well. From Service Workbench perspective any AWS account where you want to provision compute (EC2 instances, or SageMaker or EMR) is a member account. Therefore, if you want to use existing accounts from your organization and want to provision compute in those accounts, then you should add them into Service Workbench as member accounts.

Some useful links:
1. Read up on different concepts (main, master and member account): https://github.com/awslabs/service-workbench-on-aws/blob/master/docs/docs/user_guide/account_structure.md
2. "Using Service Workbench" section in https://github.com/awslabs/service-workbench-on-aws
3. Go to our docs at https://docs.aws.amazon.com/solutions/latest/service-workbench-on-aws/automated-deployment.html#step-2.-post-launch-tasks
Perform Gather information for post-launch tasks in the account where SWB is deployed, then perform Onboard AWS account in the account that you want to enable, then lastly Configure accounts, users, projects, and indexes.

Let me know if you have any further questions

--
Jeet

**Comment by zaro0508** [comment]
thanks for the info @jn1119 .  A few more questions if you don't mind..

* The documentation provides some info on manually creating [member acounts](https://github.com/awslabs/service-workbench-on-aws#using-service-workbench), [workspaces](https://github.com/awslabs/service-workbench-on-aws#creating-a-workspace) and [studies](https://github.com/awslabs/service-workbench-on-aws#create-a-study).  I'm wondering if the workbench provides a way to automate those steps? Maybe through an API or something?


* It looks like, by default, the workbench provisions products into public subnets.  Placing resources in public subnets would make access pretty easy however we prefer putting all our instances (rstudio, jupyter, etc..) into private subnets for more secure environments.  We typically set up a VPN to allow accessing resources in private subnets.  Does the service workbench provide an option to easily set up a VPC (with public/private subnets and a NAT) to host its service catalog products?

**Comment by jn1119** [comment]
* For member accounts, workspaces and studies there are APIs but we are still working on releasing the documentation for it. So stay tuned there
* All the resources that you bring are brought in a newly created VPC owned by your account but you are right, it has access to internet gateway. Is that what you meant when you said "public subnet"?

**Comment by zaro0508** [comment]
When i say public subnet I mean instances get a public IP address and can be accessed with that public IP address.  We prefer to provision instances into a private subnet which means the instance only gets a private IP address.  Does the SC workbench help with provisioning private instances?  if so does the workbench support a way to access those private instances?

**Comment by jn1119** [comment]
When you are setting up Service Catalogue templates for provisioning your workspaces, there is an option of selecting subnetId and vpc. Usually these are just place holders, so that we can use the one we created in the provisioning account. But you are free to hardcode it to your own VPC and Subnet.

**Comment by zaro0508** [comment]
thanks for the aws doc reference @jn1119.  I see that we can create custom VPCs with private subnets which would allow us to provision instances into the private subnet.  I'm still not sure how we should provide access to those instances.  Would a VPN be the recommended way to access?

**Comment by jn1119** [comment]
Apologies for not completely parsing your question. Currently, Service Workbench 'connections' feature assumes that there is a public IP address attached to EC2 instance which users can use to SSH/RDP based on environment type. We haven't add functionality of making connections work for private VPC and Subnet. Was there some specific environment type- EC2 Windows/Linux/RStudio or SageMaker you were interested in setting up? I am sure there will be public documentation in AWS that can be followed in order to get to those instances (without going through Service Workbench). I will be happy to help and take some requirements as well so that we can add this feature in Service Workbench too.

**Comment by zaro0508** [comment]
Yes, we are interested in setting up all of those env types 😄 .  We know how to setup access to private instances, we typically do it thru a VPN.  What I don't know is whether the workbench has something built in to easily allow access to private instances (VPN or otherwise).  If there isn't something built in I was looking for a recommended approach to solve this specific use case.  Our use case includes adding AWS accounts from other organizations to the workbench so I'm not even sure a VPN is a viable solution.

**Comment by rsmayda** [comment]
> What I don't know is whether the workbench has something built in to easily allow access to private instances (VPN or otherwise)

Service Workbench does not currently have the functionality of making connections to private VPC and Subnets. 

We would love to gather requirements around this. Synthesizing the conversation above, do these requirements seem right?
- As a Reacher/Admin I should be able to create a workspace within a private VPC/Subnet
- As a Researcher/Admin I should be able to access the private workspace from the Service Workbench UI

**Comment by mhebrard** [comment]
Hi @rsmayda and @zaro0508 
The ability to provide both "easy to deploy" computing infra and sharable access-controlled data collections is particularly appealing to us. However, because workspaces are deployed on public-subnets, users are able to eventually connect to other resources (S3, scp, ...) and copy data outside of the confines of the Service-Workbench's buckets (studies)
Creating (and providing access to) workspaces residing in private-subnets seems aligned with our use case (prevent eventual data egress) and this issue / call for requirement.
* As an Admin I should be able to configure workspaces that resides within a private VPC/Subnet
* As a Researcher/Admin I should 
  - be able to access private-subnet-deployed workspaces (linked to selected studies) from the Service Workbench UI 
  - not be able to access other S3 buckets outside of Service-Workbench
  -  not be able to scp, sftp , ... data out
 
Thanks
Best

**Comment by nguyen102** [comment]
Hi, in version [4.0.0](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v4.0.0) of SWB we released a feature to allow SWB to launch workspaces in private subnets. Since the workspaces are in private subnets, the workspaces do not have access to the internet. Therefore, users can connect to the workspace using AppStream. Please refer to the release notes above for more information about SWB with AppStream.

However, I would recommend you deploy our latest code version, which is version [5.0.0](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.0.0). That version includes our latest security updates as well as the AppStream feature.
