### ISSUE TITLE
what is the S3Mounts configuration in product import?

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#299]
I have installed a fresh SC workbench.  I can login and browse around.  I can add an AWS account, setup an index, setup a project, associate it with an index and assign a project admin user to it.  I am now attempting to "import" the `EC2 Linux-v1` product into "workspace types".  In the configurations step there's a required [S3Mounts parameter](https://pasteboard.co/JNC7NMO.png).  What is that?  what is it for?  and what should an S3Mounts json look like?

```
S3Mounts
A JSON array of objects with name, bucket, and prefix properties used to mount data
```

**Comment by SanketD92** [comment]
Hello, thank you for the question. The S3Mounts parameter holds the list of studies the user wishes to mount on the workspaces provisioned using that configuration. We recommend entering the placeholder value `${s3Mounts}` so that it picks up whichever studies dynamically as chosen by the user prior to provisioning the workspace using this configuration.

**Comment by zaro0508** [comment]
Thanks @SanketD92
