### ISSUE TITLE
Cannot connect to EMR-v1

### ISSUE THREAD

**Issue by mhebrard** [awslabs/service-workbench-on-aws#361]
Hi, 

I was able to deploy service-workbench using the CFN find in the section [Automated deployment](https://docs.aws.amazon.com/solutions/latest/service-workbench-on-aws/automated-deployment.html)  on AWS Solutions Implementations

* I am able to create an EC2 and connect to it by SSH
* I am able to create a Sagemaker and connect to jupyter
* Problem raise with EMR:

I am able to create an EMR using the EMR-v1 workspace type. I can see that the EMR is available from the workbench UI. I am also able to see the EMR running in the AWS webconsole.

The problem is that the link to connect within the workbench send me to a brocken URL:
`http://ec2-xxx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com:8192/`
> This site can’t be reached

* Note sure if that is related, but I noticed that for Sagemaker the URL is not directly the `ec2...` but an url `basicnotebookinstance...`
* another solution acceptable in my use-case would be to get a SSH connection to the EMR master node the same way the EC2 Linux v1 is providing it.

Any help to enable EMR through service workbench ?

**Comment by Bingjiling** [comment]
Hi @mhebrard, thanks for reaching out! We discovered a bug last week regarding EMR instance connection when there's study attached. The root cause of the issue was the auto upgrade from Jupyter Lab 2 to Jupyter Lab 3 introduced by a script. We're focusing on the fix this week. 

I'm wondering if you could try creating a EMR instance without a study attached? If you could connect to the EMR instance without a study, then we can confirm the issue you're seeing is the same.

**Comment by mhebrard** [comment]
Hi @Bingjiling, I created a EMR instance without study attached, and I am not able to connect to it.

By going to "Workspace Types", Selecting "EMR-v1" (that is currently in "not Approved" status), ant click on "Test launch".
Waiting for the workspace to be "available", then click on "connections" and "Main URL for Jupyter Notebook - connect"
Thay open a new window at the address "http://ec2-###.ap-southeast-1.compute.amazonaws.com:8192/" and google chrome displays a message "This site can’t be reached"

On the AWS web console I can see the EMR instance is working fine, but I cannot connect to it as I do not have the pem key.

**Comment by nguyen102** [comment]
Hi @mhebrard,

Let's try to add your IP address to the EMR Workspace by clicking on `Edit CIDR`. This will allow your IP address to access the Jupyter notebook. You can find your IP address by [googling it](https://www.google.com/search?q=what+is+my+ip+address&oq=what+is+&aqs=chrome.0.69i59j69i57j69i59l2j69i65j69i61j69i60l2.1218j0j7&sourceid=chrome&ie=UTF-8). Then add the IP address along with the suffix `/32`. 

Once you gain access to the Jupyter web url, it will ask you for a password. The password is `go-research-on-aws`

**Comment by mhebrard** [comment]
Hi @nguyen102

After further test, it happen that my institution have a firewall that is restrict quite drastically the ports. The default port of jupyterlab is closed by this institutional firewall, that is why I cannot connect to the notebook.

I tested the connection from outside my institution and I am able to connect to EMR notebook without issue.

Sorry for the trouble

I guess I will have to edit the port on which jupyterLab is served.
Is there a way to edit that while the service workbench is running ?
If not, is there a way to edit the EMR template but still use the service workbench CFN found on AWS documentation ?

**Comment by nguyen102** [comment]
Hi, 

By default Jupyter Lab runs on port 8192. We currently do not support changing the default port. With that being said, SWB is an open source tool and can be modified to fit your use case. I'll provide some guidance below of where to look in changing the port.

We use a third party package with scripts for setting up JupyterLab on EMR. Specifically this is the [relevant script](https://github.com/hms-dbmi/hail-on-AWS-spot-instances/blob/master/src/jupyter_notebook_config.py#L3) we want to edit.

The port of 8192 can be edited on [line 50](https://github.com/awslabs/service-workbench-on-aws/blob/d862fccc3912a5b41aefdd934a55d27cfe214a7a/main/solution/machine-images/config/infra/provisioners/provision-hail.sh#L49), similar to what is being done on line 49 to change the default password. 

Once that change is made you want to rebuild the AMI image for your EMR Workspace and upload that to your AWS account. 

You will also need to make changes to the default port being opened for Jupyter Lab in CFN. Link [here](https://github.com/awslabs/service-workbench-on-aws/blob/fe8e8911cca52e260980f47d7c99051d5c0aec68/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/emr-cluster.cfn.yml#L115). You will want to update your environment so that service catalog picks up this new version. 

Once you've done these steps, you can import the new EMR Workspace type.

**Comment by mhebrard** [comment]
Thanks for the guidance. I am currently looking into it.
I ll fork the project and start a branch to fit my use case.

Is there a way to re-build the AMI, upload and update a "already-deployed" SWB. Or it needs to kill the old SWB and re-deploy the full new stack ?

**Comment by nguyen102** [comment]
To rebuild and upload the AMI, you can follow the directions here
https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/machine-images/README.md#package-and-deploy

After you make changes to the EMR CFN, you can update your environment by running `./scripts/environment-deploy.sh <STAGE>` in the root directory. That should update your Workspace Types with a new EMR version. Go to Workspace Type and Import the new version. For the configuration use the new AMI ID that you created earlier.
