### ISSUE TITLE
Question: Workbench and Bootstrap actions

### ISSUE THREAD

**Issue by mhebrard** [awslabs/service-workbench-on-aws#443]
Hi, 

Outside of Workbench, I have a CloudFormation template that create a EMR and install software on it.
Each software installation is managed within a shell script that is store on S3 and called by the CloudFormation template through bootstrap actions.

Now I wish to integrate a similar EMR + software within service workbench.
* I succeed to deploy service workbench.
* I succeed to add a new workspace type that is a custom EMR
  * adding a `.cfn.yml` file in `./addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/`
  * adding a new item to the catalogue in `./addons/addon-base-raas/packages/base-raas-post-deployment/lib/steps/create-service-catalog-portfolio.js`

Question is to install software on the custom EMR workspace, what is the recommanded path ?

1> If I can have the `.cfn.yml` executing bootstrap actions, then where should I place / store the relevent shell scripts ?
2> Is it better to create an AMI specific to the custom EMR ? if yes, how do I create a custom image and install software on it ?

Best

**Comment by Bingjiling** [comment]
Hi @mhebrard, 

thanks for reaching out! Both 1 and 2 are feasible in SWB and there're pros and cons in each option. 

Existing approaches in SWB:

For option 1, SWB has a [bootstrap script](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/post-deployment/config/environment-files/bootstrap.sh) that's loaded through S3 on instance launch. This script is uploaded to S3 bucket during deployment, and the S3 address is passed to CFN template through parameter [EnvironmentInstanceFiles](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml#L34). This script is shared among different types of workspaces, and it has the ability to check the type of workspaces it is in. 

For option 2, SWB uses Packer to build custom machine images, and you can reference the example [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/machine-images/config/infra/provisioners/provision-hail.sh) for installing software on custom EMR workspace. 

Pros vs. Cons:

For option 1, the pro here is ease of change/update the script. Since the script is sourced from the S3 bucket on instance launch, once the script update is deployed through `environment-deploy.sh`, instances launched after that would immediately gets the latest script. The con here is the difficulties in discovering software install issue and trouble shooting. If the boostrap script fails during instance launch for software install, the only way to discover this issue is to log in the instance and check directly. 

For option 2, the pro here is the certainty of the same set of software always be available in the instance launched using the custom AMI. The con here would be the more complicated process to update compared to option 1. To update AMI, first the new image need to be created, then a new workspace configuration need to be created to include the new AMI id, and users need to use the newly created configuration to use the new AMI. 

Hope this helps. Please let me know if you have any questions. 

Thanks,
Yanyu

**Comment by mhebrard** [comment]
Hi @Bingjiling,

Thanks to point me to the good files.

From what I see, I will follow the option 1. It is closer to what I was doing outside of SWB and fits better my current needs.
I could add my custom booststrap action scripts within [environment-files](https://github.com/awslabs/service-workbench-on-aws/tree/mainline/main/solution/post-deployment/config/environment-files) and reference them in my custom EMR template as :

```
- Name: My-Boostrap
    ScriptBootstrapAction:
      Path: !Sub '${EnvironmentInstanceFiles}/my-script.sh'
```

I'll try that approach and let you know if any issue

**Comment by Bingjiling** [comment]
Hi @mhebrard,

That sounds great! One extra detail on option 1, the script needs to be downloaded and run from a local path, you can reference the example [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml#L169) for more detail.
