### ISSUE TITLE
[Bug] Blank Page on Sagemaker Workspace Connect

### ISSUE THREAD

**Issue by jol-ster** [awslabs/service-workbench-on-aws#509]
**Describe the bug**
When connecting to Sagemaker workspaces, there is an intermittent issue where a blank browser launches instead of Sagemaker.  The issue presents for workspaces that are newly created as well as for workspaces that were already created, but were stopped and are being restarted.

**To Reproduce**

STEP 1: Login as an Admin 
STEP 2: Create a workspace (SageMaker)
STEP 3: Start the Workspace 
STEP 5: Click "Connect"
STEP 6: A new blank web browser tab opens 
STEP 7: Click "Connect" again, another blank web browser tab opens

User receives a "Something Went Wrong" general error in SWB at Step 6

In the client logs for the browser, there is also this error noted:
              "name": "x-cache",
              "value": "Error from cloudfront"
   

**Expected behavior**
Sagemaker workspace launch in browser

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed 3.0.0

**Additional context**
User has cleared cache and it solved the issue, but for one of her employees clearing the cache did not solve the issue. 

The issue is experienced approximately once a week. Sometimes clearing cache solves the issue. Other times going to incognito, and it does not solve the issue.

**Comment by nguyen102** [comment]
The relevant code snippet for this issue is [here](https://github.com/awslabs/service-workbench-on-aws/blob/7988c933d5f4d6c9878249a7521d64d891707824/addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentHttpConnections.js#L60).

I was unable to reproduce this issue (I'm using Chrome 90.0.4430.212) , but let's try to track this issue down.

Are we unable to get the Sagemaker URL or is the browser failing to refer the user to the Sagemaker url?

To check if the browser is getting the Sagemaker URL correctly:
1. Go to the Sagemaker workspace and click the connection button to open the "HTTP Connections" card 
2. Open the network tab in Chrome Inspect tool
3. Clear all of the network activity
4. Click on the `url` row on the sidebar
5. In the new tab that opens up, select the sub tab for `response`.
6. Check if a `url` is provided and try navigating to that `url` in the browser.

If the URL is valid and you can can navigate to the Sagemaker instance that way, then the issue is with the browser failing to redirect the user.

https://user-images.githubusercontent.com/3661906/120824482-84a88d80-c526-11eb-883b-13d9b4cfa7f4.mov
Here's a video of the process.

Please follow the instructions above to help us debug what is the cause of the issue.
