### ISSUE TITLE
[Enhancement] Force-logout upon token expiration

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#589]
**Describe the bug**

**To Reproduce**
After idle time on UI, we always get this non User friendly error

**Expected behavior**
Instead the user should be sickout the platform and going back to login page

**Screenshots**

**Versions (please complete the following information):**
v3.3.0 but this was since v1. never took the time to repport it

**Additional context**

**Comment by SanketD92** [comment]
Hello @avillach, the fix for force-logout upon token expiration has been released in [v3.3.1](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v3.3.1). This would ensure users don't experience an unresponsive page (usually caused by token expiration), irrespective of the idle-timeout.

Hope this helps.
