### ISSUE TITLE
[Bug] Looking at Study details in data-sources fails

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#590]
**Describe the bug**
From Admin page https://service-workbench.hms.harvard.edu/data-sources
when I try to open ANY study I get a new total blank page

**To Reproduce**
https://service-workbench.hms.harvard.edu/data-sources
click on ANY study

**Versions (please complete the following information):**
v3.3.0

**Additional context**
This is the first time that I configure studies as BYOB in SWB PROD.   worked fine before on SWB DEV
So I don't know if this is related to a newer version

**Comment by avillach** [comment]
My bad, I didn't meant to close it. Still open issue

**Comment by jn1119** [comment]
Thanks Paul for reaching out, I have started looking into this issue and will post an update shortly.

**Comment by jn1119** [comment]
I used 3.3.0 release and created couple of new data sources in my test environment. Unfortunately, I wasn't able to reproduce the issue. We can try the following as next steps:

1. Do the studies show up under studies/organization tab and are you able to use them via a workspace?
2. Can you try another browser and see if you see the same issue?
3. Do you see any errors in network tab when you go to the data-sources tab. Note that the video you uploaded expands the study but the relevant data-sources API calls had already been called. In order to see the errors coming from data-sources tab just login to service workbench like you normally do, and before clicking on data-sources tab open the network tab. Any related cloudwatch logs would also be useful.

**Comment by jn1119** [comment]
Also, can you make sure that both your data sources stacks are up to date (perhaps you can re-run them?). I wonder if something has changed in the account which has those buckets.

**Comment by jn1119** [comment]
Hey Paul, we will be releasing v3.3.1 today. We were able to reproduce the bug if study permissions contain a user that was deleted by admin. If that's what is happening in your case, v3.3.1 should fix this issue.

**Comment by jn1119** [comment]
Version [3.3.1](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v3.3.1) is now released. Can you try it out and let us know if your issue is fixed. Also instead of using the `network` tab in developer tools, can you select the `console` instead and paste the error you end up seeing if UI crashes. Thanks.

**Comment by avillach** [comment]
issue resolved with 3.3.1. Thanks!
