### ISSUE TITLE
[Misc] How to add bash script to Sagemaker notebook lifecycle configuration? 

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#667]
Where can I configure the bash script launched 
1) at each start
2) at creation
of a Sagemaker  jupyternotbook

For example I would like to add at each start after the "Stop Idle Script"
#!/usr/bin/env bash
set -e
# OVERVIEW
# This script installs the specified packages in a single SageMaker conda environments.
nohup sudo -b -u ec2-user -i <<'EOF'
conda install "r-devtools" --name "R" --yes
conda install "r-rentrez" --name "R" --yes
conda install "r-XML" --name "R" --yes
conda install "r-BiocManager" --name "R" --yes
conda install "r-oligo" --name "R" --yes
conda install "r-pd.hugene.1.0.st.v1" --name "R" --yes
conda install "r-annotate" --name "R" --yes
conda install "r-hugene10sttranscriptcluster.db" --name "R" --yes
conda install "r-VariantAnnotation" --name "R" --yes
conda install "r-org.Hs.eg.db" --name "R" --yes
conda install "r-TxDb.Hsapiens.UCSC.hg19.knownGene" --name "R" --yes
conda install "r-BSgenome.Hsapiens.UCSC.hg19" --name "R" --yes
conda install "r-Matrix" --name "R" --yes
conda install "r-irlba" --name "R" --yes
conda install "r-threejs" --name "R" --yes
conda install "r-msa" --name "R" --yes
conda install "r-seqinr" --name "R" --yes
conda install "r-adegenet" --name "R" --yes
conda install "r-ggtree" --name "R" --yes
conda install "r-tidyverse" --name "R" --yes
conda install "r-dplyr" --name "R" --yes
conda install "r-tidyr" --name "R" --yes
conda install "r-data.table" --name "R" --yes
conda install "r-ggplot2" --name "R" --yes
EOF

 - Release Version installed 3.3.1

Thanks!

Paul

**Comment by nguyen102** [comment]
To add additional script on start of a sagemaker notebook, you can add the code [here](https://github.com/awslabs/service-workbench-on-aws/blob/b9c1a721e90702825a4ca0ec8b2b7adb52d63a99/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml#L243)

Note that this will create a new SC version for Sagemaker and you will have to import that Workspace into SWB.

___
To add additional software at creation of Sagemaker, add your code [here](https://github.com/awslabs/service-workbench-on-aws/blob/c95a323ca00f116a80232eb93a8dd65737a2d776/main/solution/post-deployment/config/environment-files/bootstrap.sh#L75). This code change will not require importing a new Workspace into SWB, since this script will be executed for all workspaces. In this case, if the new code is put inside the `if block` for Sagemaker, only Sagemaker workspaces will get the new change.

The current code is set up to install dependencies from an S3 bucket instead of the internet. Those packages are stored [here](https://github.com/awslabs/service-workbench-on-aws/tree/b9c1a721e90702825a4ca0ec8b2b7adb52d63a99/main/solution/post-deployment/config/environment-files/offline-packages) and automatically gets uploaded to S3 on SWB Post deployment. To follow this pattern, you should download the packages that you need and put it in the **offline-packages** directory as well. You would then install the libraries from that folder. [Here](https://unix.stackexchange.com/a/174485) is some information on how to download packages locally.
