### ISSUE TITLE
[Bug] IdP deployment issue

### ISSUE THREAD

**Issue by angelosnm** [awslabs/service-workbench-on-aws#676]
We have deployed successfully the app and we are now focusing on configuring IdP.

The below needed parameters are applied on our {stage}.yml and we have configured our sample-idp-metadata.xml file as well although when we rerun deployment script the below error comes up.

•	fedIdpIds
•	fedIdpNames 
•	fedIdpDisplayNames 
•	fedIdpMetadatas

![image](https://user-images.githubusercontent.com/28690845/130951041-114c7341-2e3e-4704-896d-6021b540f46a.png)

**Comment by SanketD92** [comment]
Hello @agelosnm, thank you for opening this issue.

The error suggests there was a problem performing an AWS SDK operation. Uploading and retrieving the metadata file with respect to the deployment artifact S3 bucket are some of the critical operations while setting up IdP with SWB.

Could you verify the `saml-metadata` folder in your deployment bucket in S3 (name ends with `dep-artifacts`) contains the updated metadata file?

**Comment by angelosnm** [comment]
> Hello @agelosnm, thank you for opening this issue.
> 
> The error suggests there was a problem performing an AWS SDK operation. Uploading and retrieving the metadata file with respect to the deployment artifact S3 bucket are some of the critical operations while setting up IdP with SWB.
> 
> Could you verify the `saml-metadata` folder in your deployment bucket in S3 (name ends with `dep-artifacts`) contains the updated metadata file?

Hi @SanketD92!

Thanks for your reply!

I confirm that `saml-metada` folder contains the updated .xml file.
Although, it seems that  the file cannot be accessed from the deployment script , even when allowing full public access on the S3 bucket.

**Comment by SanketD92** [comment]
@agelosnm, thank you for your prompt response.

A couple of things that could be causing this issue:

1. Could you confirm you're able to access the metadata file via AWS CLI, with the same AWS profile/IAM role used for SWB deployment? This is to make sure the IAM role has the required permissions to read files in S3.
2. Could you confirm there is no spelling mistake in specifying the metadata filename? S3 throws AccessDenied if the requested file does not exist on the bucket.

Also, could you send the log generated prior to this error? This will help us troubleshoot which AWS operation could be causing this issue.

**Update:**

I wasn't able to reproduce the error when upgrading from non-IdP to IdP for a SWB deployment.

Also, there is a way to just execute post-deployment steps (instead of redeploying SWB completely) for quicker debugging:
1. Go to the post-deployment directory: `cd main/solution/post-deployment`
2. Make sure post-deployment stack is up to date: `pnpx sls deploy -s <stage>`
3. Run post deployment steps: `pnpx sls invoke local -f postDeployment -s <stage>`

**Comment by angelosnm** [comment]
> @agelosnm, thank you for your prompt response.
> 
> A couple of things that could be causing this issue:
> 
> 1. Could you confirm you're able to access the metadata file via AWS CLI, with the same AWS profile/IAM role used for SWB deployment? This is to make sure the IAM role has the required permissions to read files in S3.
> 2. Could you confirm there is no spelling mistake in specifying the metadata filename? S3 throws AccessDenied if the requested file does not exist on the bucket.
> 
> Also, could you send the log generated prior to this error? This will help us troubleshoot which AWS operation could be causing this issue.
> 
> **Update:**
> 
> I wasn't able to reproduce the error when upgrading from non-IdP to IdP for a SWB deployment.
> 
> Also, there is a way to just execute post-deployment steps (instead of redeploying SWB completely) for quicker debugging:
> 
> 1. Go to the post-deployment directory: `cd main/solution/post-deployment`
> 2. Make sure post-deployment stack is up to date: `pnpx sls deploy -s <stage>`
> 3. Run post deployment steps: `pnpx sls invoke local -f postDeployment -s <stage>`

Hi @SanketD92!

I confirm points 1 & 2 of your last.

Upon applying the altrenate post-deployment steps described above everything ran smoothly. :)
Thanks for your feedback!
