### ISSUE TITLE
[Bug] Research workspaces with "Stopping" status never ending

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#698]
**Describe the bug**
When creating research workspaces in SWB, some of them stay in a permanent "stopping" status, with the only option of terminating the workspace.

**To Reproduce**
This issue appears from time to time, but without a clear pattern. Sometimes this happens when the user manually clicks on Stop and other times with the autostop. 

**Expected behavior**
That the research workspace ends up stopping and with the option to start it later. 

**Screenshots**
![Screen Shot 2021-09-08 at 12 01 33 PM](https://user-images.githubusercontent.com/19646530/132544966-e0cfd128-f93b-4911-a554-fbc1a10bbc97.png)

**Versions (please complete the following information):**
Release Version installed: 3.3.1

**Comment by jol-ster** [comment]
Hello - a couple of questions to help recreate the issue.
1) Is this occuring during actual workspace creation, or after successful creation when the workspace is being used and managed?  I am thinking the latter, but waned to confirm since you mention that the issue happens when a workspace is being created  
2) Is this only occurring for Sagemaker workspace types, or is it happening with others as well?

**Comment by aGutierrezSacristan** [comment]
Hi @jol-ster ,
1. If happens after successful creation when the workspace is being used. 
2. So far, only for Sagemaker workspaces
Thanks

**Comment by nguyen102** [comment]
There was an issue with Sagemaker propagating the correct lifecycle status to SWB. This has since been fixed with this PR.
https://github.com/awslabs/service-workbench-on-aws/pull/703

You can deploy the latest version of SWB to receive the fix.
