### ISSUE TITLE
[Bug] studies with admin permission but denied to save any changes

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#706]
**Describe the bug**
We have a organization study with two levels of permissions: Admin and  Read only. 
When we create a workspace with this study, the people listed as admin, and login as admin, cannot edit any of the files, or create/upload new ones. We get two distinct errors. 
- "Permission denied": When without making any change in the notebook try to save it 
- "Unexpected error: no such file or directory" When doing some edits in the notebook and then try to change it.

**To Reproduce**
1. Go to 'studies' -> 'organization', create a study "MyStudy" with admin and read only permissions
2. In admin add your email: xxx@gmail.com
3. Once the study is created, select it and create a workspace with the study on it.
4. Start the workspace, access to the folder studies and the folder "MyStudy". 
5. Try to create a new notebook: click on new, R notebook: then you get Permission denied.
6. If you have previously uploaded through the AWS console some files in the specific folder located in the s3 bucket, you can see the files.
7. Open the files previously loaded and click on "save" --> you will get the permission denied error.
8. Open the same file previously loaded and do some changes on the notebook then click on save --> you will get the unexpected error, not such file or directory.

**Expected behavior**
The users added as admin can make changes, while the ones added as read only cannot. 

**Screenshots**
Error when trying to create a new file there:
![Screen Shot 2021-09-11 at 9 35 08 AM](https://user-images.githubusercontent.com/19646530/132949771-ad334e41-0803-480d-8169-0a6458f0f27d.png)

Error when open a pre-loaded file via AWS console and click on save
![Screen Shot 2021-09-11 at 9 30 09 AM](https://user-images.githubusercontent.com/19646530/132949791-bafa470f-d429-4f30-8c99-54f1f5b57e51.png)

Error when open the same pre-loaded file via AWS console, make an edit and click on save
![Screen Shot 2021-09-11 at 9 29 40 AM](https://user-images.githubusercontent.com/19646530/132949784-f3c4eea9-0ca6-43ca-b4e6-e687b7e9ea90.png)

**Versions (please complete the following information):**
Release Version installed: 3.3.1

**Comment by SanketD92** [comment]
Sounds like the organization study you're referring to is linked to a data source account, and the data source admin must have granted only ReadOnly access to the bucket.

The study admin can only make changes to users listed in the R/O and R/W permission levels (being a study admin does not guarantee R/W access to the study). So in order to have R/W access to such a data source study, (1) the data source account admin must configure it to allow R/W access, and (2) the user must be listed under the R/W permission level on the study.

Let me know if any of my assumptions are wrong.

**Comment by aGutierrezSacristan** [comment]
Thanks @SanketD92. I think I understood it. But then we should not be able to do any changes on any other studies created in the same way and where we are only admin and not read-and-write, but where we are... 

My guess after is that even if the admin users are not listed in the read-and-write, if there is at least one additional person added with read-and-write we can do any changes as admin. But since in the study there are only admins and read only then the admin cannot do any changes either. Does this make sense?

Would it be possible to add read-write permissions to a study created at the beginning with users as admin and read-only? When I click on editing the study from SWB, I can only add admins or readonly users, I cannot see the read-and-write option.

**Comment by SanketD92** [comment]
@aGutierrezSacristan, I understand your question. The reason this study does not have a R/W list associated to it is not because it's empty, but because the study was registered with R/O permission by the data source administrator (owner of the S3 bucket where this study folder resides). 

In order to get R/W access to the study, it would need to be registered accordingly by the data source administrator as follows:
![Screen Shot 2021-09-15 at 2 04 23 PM](https://user-images.githubusercontent.com/20480854/133486019-23e8885d-2aee-4726-a465-ca53a4206a26.png)

Note: Again, I'm assuming this study is associated to a data source account (since a legacy organization study would have shown both R/O and R/W user-lists, even if either list was empty).

**Comment by aGutierrezSacristan** [comment]
Got it! completely understand now! yes! when we created the study we probably selected as Access "Read only". 
Thank you so much for your detailed and great explanation! @SanketD92

**Comment by avillach** [comment]
yes, bottom line is I shouldn't have created a study with read only. It's much better to create with Read / write and add and remove as needed. 
Thanks!
