### ISSUE TITLE
[Feature Request] Create a persistent R Notebook within Sagemaker so that R libraries installed do not need to be re-installed after stop and re-start

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#759]
**Describe the bug**
 R libraries installed need to be re-installed after stop and re-start the SageMaker workspace

**To Reproduce**
1. Start a SageMaker workspace
2. Create a new R notebook
3. Install a library that is not pre-installed
4. Load the library
5. Stop the workspace
6. Start the workspace
7. Try to load the library
8. You get an error, the library needs to be re-installed

**Expected behavior**
That the libraries installed while working on a workspace are available after stopping and re-starting the workspace. 

**Versions (please complete the following information):**
 - Release Version installed v4.0.1

**Additional context**
We tried by stopping and starting the workspace directly from the AWS console and the error persist.

**Comment by Bingjiling** [comment]
Hi @aGutierrezSacristan, 

Thanks for reaching out! 

For the SageMaker library install problem, I'm wondering if this issue only exist for R notebook in SageMaker workspaces created through SWB? Or does it exists for R workspace created in any SageMaker workspaces? 

Meanwhile, SWB does provide a R Studio workspace type as well. And it is a better experience for R users compared to R NoteBook in SageMaker once it's set up. 

Thanks,
Yanyu

**Comment by jn1119** [comment]
@aGutierrezSacristan Is this a new error that came up in latest release or there was a time this was working for you?

**Comment by aGutierrezSacristan** [comment]
Hi @Bingjiling and @jn1119 for your quick response.
- It was an error that was also on the previous released
- The issue exists on the R notebooks created through SWB and in the ones created through AWS Sagemaker directly too. I tried both. 
- Yes, this is not an issue in Rstudio workspaces, in which the libraries installed are still there after the workspace is stopped and started again. 

I have been trying to narrow down the issue with the SageMaker notebook R library installation trying different things:
- When I created the notebook directly on AWS Sagemaker I  did not select any lifecycle configuration but the R installation issue persists, so probably not related to the life cycle configuration. 
- I also checked where the libraries installed are located, and in SageMaker the libraries installed are in /home/ec2-user/anaconda3/envs/R/lib/R/library, and this folder is "reset" every time the workspace is stopped. How can we know which folders are "reset" and which ones are not? any way to avoid having this folder to be "reset" when the workspace is stopped?
- For reference in the Rstudio workspace, when a library is installed is in /home/rstudio-user/R/x86_64-koji-linux-gnu-library/3.4, and this folder remains with all the changes a new libraries added after stop and start. 

Thanks!

**Comment by maghirardelli** [comment]
Hi @aGutierrezSacristan,

Thanks for all the information. We have looked into it and have put this feature request into our backlog of things to do. For a workaround that might work for your case, here is a [blog post](https://aws.amazon.com/blogs/machine-learning/creating-a-persistent-custom-r-environment-for-amazon-sagemaker/) that I followed that I succeeded in making a persistent environment to use between Sagemaker Notebooks and well as between starting/stopping the same Notebook. Long story short: you can create a Lifecycle Configuration to fetch an environment configuration from S3 and then will be able to use that as an R Notebook within a Sagemaker Notebook. However, this is not a permanent fix because there are some downsides to this workaround (read these after reading the blog post for context):
- It has to be done through the AWS Sagemaker Console and cannot be done through the SWB UI.
- Once the environment setup has been created and saved to S3, you have to manually attach the Lifecycle Configuration to all Sagemaker Notebooks. They must be stopped and started for it to take effect.
- If you create a new Sagemaker Notebook through the AWS Console, it is easy to attach the Lifecycle Configuration.
- If you create a new Sagemaker Workspace through the SWB UI, there is no way to attach the Lifecycle Configuration. An admin with access to the AWS Console would have to attach the policy after the workspace has been created.

For those reasons, I am going to mark this as a feature request and put it in our backlog.

Let me know if you have any more questions!
Marianna

**Comment by aGutierrezSacristan** [comment]
Hi @maghirardelli, 

Thank you so much for the detailed explanation and the workaround. 
Looking forward to the enhancement. 

Thanks, 

Alba
