### ISSUE TITLE
[Bug] get-info.sh file not working

### ISSUE THREAD

**Issue by aswin2025** [awslabs/service-workbench-on-aws#998]
**Describe the bug**
We followed the steps to install the workbench using AWS Cloud9 and EC2 instances. Deployment was successful, but the summary info that contains the API endpoints and URL is not obtained.

**To Reproduce**
1. Deploy the workbench using the AWS Cloud9.
2. Expected Result doesn't match the actual result. The summary analysis is not obtained

**Expected behavior**
<img width="641" alt="expected" src="https://user-images.githubusercontent.com/78466113/171565641-9d5e1e46-4453-4e45-bb84-6a4fdbdc0d17.PNG">

**Actual Behavior**

<img width="504" alt="actual" src="https://user-images.githubusercontent.com/78466113/171567660-4095e770-e97e-45b0-bc78-dbf770bcbc63.PNG">

**Comment by maghirardelli** [comment]
Hi @aswin2025!
This is likely due to a [PNPM issue](https://github.com/pnpm/pnpm/issues/4684) of PNPM version 7 (v7.1.2 as of May 2022). You can run the following command to check your `pnpm` version: `pnpm --version`.

Workaround: Uninstall `pnpm` and reinstall the latest `pnpm` v5
```
npm uninstall -g pnpm
npm install -g pnpm@latest-5
pnpm --version
```

We'll be updating the documentation shortly. Thank you for bringing this to our attention. Let me know if the error persists after this workaround, or feel free to close the issue if this fixes it for you!

**Comment by aswin2025** [comment]
Thanks for your response @maghirardelli. The workaround helped in resolving this issue
